<script setup lang="ts">
definePageMeta({ middleware: ['auth', 'barber'], layout: 'dashboard' })
interface Profile { name: string, email: string, especialidades: string, descripcion: string, foto_url: string | null, calificacion_promedio: number | null, total_resenas: number, member_since: string, years_experience: number, portfolio_total: number, stats: { citas_hoy: number, completadas_mes: number, total_completadas: number } }
const { apiFetch } = useApi(); const { data, pending, error, refresh } = await useAsyncData<Profile>('barber-profile', () => apiFetch('/barber/me')); const especialidades = ref(''); const descripcion = ref(''); const foto = ref<File | null>(null); const saving = ref(false); const message = ref('')
watchEffect(() => { if (data.value && !especialidades.value && !descripcion.value) { especialidades.value = data.value.especialidades; descripcion.value = data.value.descripcion } })
function selectPhoto(event: Event) { foto.value = (event.target as HTMLInputElement).files?.[0] ?? null }
async function save() { saving.value = true; message.value = ''; try { const body = new FormData(); body.append('especialidades', especialidades.value); body.append('descripcion', descripcion.value); if (foto.value) body.append('foto', foto.value); await apiFetch('/barber/profile', { method: 'POST', body }); message.value = 'Perfil actualizado.'; foto.value = null; await refresh() } catch (err: unknown) { message.value = (err as { data?: { message?: string } })?.data?.message ?? 'No se pudo guardar.' } finally { saving.value = false } }
</script>
<template><div class="p-4 sm:p-6 lg:p-8"><header class="mb-6"><p class="text-xs uppercase tracking-widest text-muted">Mi espacio</p><h1 class="mt-1 text-2xl font-semibold text-ink">Mi <span class="text-gold">Perfil</span></h1><p class="mt-1 text-sm text-muted">Actualiza tu presentacion publica.</p></header><p v-if="pending" class="text-muted">Cargando...</p><p v-else-if="error" class="text-red-400">No se pudo cargar tu perfil.</p><div v-else-if="data" class="grid gap-6 lg:grid-cols-[320px_1fr]"><aside class="space-y-4"><section class="ui-card p-6 text-center"><img v-if="data.foto_url" :src="data.foto_url" :alt="data.name" class="mx-auto h-28 w-28 rounded-full object-cover"><div v-else class="mx-auto flex h-28 w-28 items-center justify-center rounded-full bg-gold/10 text-3xl font-black text-gold">{{ data.name.slice(0,2).toUpperCase() }}</div><h2 class="mt-4 text-xl font-black text-ink">{{ data.name }}</h2><p class="text-sm text-gold">{{ especialidades.split(',')[0] || 'Maestro barbero' }}</p><div class="mt-5 grid grid-cols-3 border-t border-line pt-4"><div><b class="text-ink">{{ data.calificacion_promedio ?? '—' }}</b><p class="text-xs text-muted">Rating</p></div><div><b class="text-ink">{{ data.stats.total_completadas }}</b><p class="text-xs text-muted">Citas</p></div><div><b class="text-ink">{{ data.years_experience }}a</b><p class="text-xs text-muted">Exp.</p></div></div></section><section class="ui-card p-5 text-sm"><p class="text-xs uppercase text-muted">Cuenta</p><p class="mt-3 font-bold text-ink">{{ data.email }}</p><p class="mt-1 text-muted">{{ data.total_resenas }} resenas · {{ data.portfolio_total }} trabajos</p></section></aside><form class="ui-card space-y-5 p-6" @submit.prevent="save"><div><label class="mb-1 block text-xs uppercase text-muted">Especialidades</label><input v-model="especialidades" maxlength="1000" class="w-full rounded-lg border border-line bg-main px-3 py-2 text-ink" placeholder="Fade, barba, colorimetria..."></div><div><label class="mb-1 block text-xs uppercase text-muted">Sobre mi</label><textarea v-model="descripcion" maxlength="1000" rows="6" class="w-full rounded-lg border border-line bg-main px-3 py-2 text-ink"/></div><div><label class="mb-1 block text-xs uppercase text-muted">Foto de perfil</label><input type="file" accept="image/jpeg,image/png,image/webp" class="w-full text-sm text-muted" @change="selectPhoto"></div><p v-if="message" class="text-sm text-gold">{{ message }}</p><button :disabled="saving" class="rounded-lg bg-gold px-5 py-3 text-sm font-bold text-black disabled:opacity-50">{{ saving ? 'Guardando...' : 'Guardar cambios' }}</button></form></div></div></template>
