<script setup lang="ts">
definePageMeta({ middleware: ['auth', 'barber'], layout: 'dashboard' })
interface Day { day_of_week: string, start_time: string, end_time: string, is_active: boolean }
const names: Record<string, string> = { monday: 'Lunes', tuesday: 'Martes', wednesday: 'Miercoles', thursday: 'Jueves', friday: 'Viernes', saturday: 'Sabado', sunday: 'Domingo' }; const order = Object.keys(names); const { apiFetch } = useApi()
const { data, pending, error } = await useAsyncData<{ schedules: Day[] }>('barber-schedule', () => apiFetch('/barber/schedule')); const days = ref<Day[]>([])
watchEffect(() => { if (data.value && !days.value.length) days.value = order.map(key => data.value?.schedules.find(d => d.day_of_week === key) ?? { day_of_week: key, start_time: '09:00', end_time: '18:00', is_active: key !== 'sunday' }) })
const saving = ref(false); const message = ref(''); function copyToAll(source: Day) { days.value = days.value.map(day => ({ ...day, start_time: source.start_time, end_time: source.end_time, is_active: source.is_active })) }
async function save() { saving.value = true; message.value = ''; try { await apiFetch('/barber/schedule', { method: 'PUT', body: { schedules: days.value.map(d => ({ ...d, start_time: d.start_time.slice(0,5), end_time: d.end_time.slice(0,5) })) } }); message.value = 'Horario actualizado correctamente.' } catch (err: unknown) { message.value = (err as { data?: { message?: string } })?.data?.message ?? 'No se pudo guardar.' } finally { saving.value = false } }
</script>
<template><div class="p-4 sm:p-6 lg:p-8"><header class="mb-6"><p class="text-xs uppercase tracking-widest text-muted">Mi espacio</p><h1 class="mt-1 text-2xl font-semibold text-ink">Mi <span class="text-gold">Horario</span></h1><p class="mt-1 text-sm text-muted">Define tus dias laborales y horas de atencion.</p></header><p v-if="pending" class="text-muted">Cargando...</p><p v-else-if="error" class="text-red-400">No se pudo cargar tu horario.</p><form v-else class="space-y-3" @submit.prevent="save"><article v-for="day in days" :key="day.day_of_week" class="ui-card grid gap-4 p-5 sm:grid-cols-[1fr_auto_auto_auto] sm:items-center" :class="{ 'opacity-60': !day.is_active }"><label class="flex items-center gap-3 font-bold text-ink"><input v-model="day.is_active" type="checkbox" class="h-5 w-5 rounded border-line">{{ names[day.day_of_week] }} <span class="text-xs font-normal text-muted">{{ day.is_active ? 'Laboral' : 'Descanso' }}</span></label><input v-model="day.start_time" :disabled="!day.is_active" type="time" required class="rounded-lg border border-line bg-main px-3 py-2 text-sm text-ink"><input v-model="day.end_time" :disabled="!day.is_active" type="time" required class="rounded-lg border border-line bg-main px-3 py-2 text-sm text-ink"><button type="button" class="text-xs font-bold text-gold" @click="copyToAll(day)">Copiar a todos</button></article><p v-if="message" class="text-sm text-gold">{{ message }}</p><button :disabled="saving" class="rounded-lg bg-gold px-5 py-3 text-sm font-bold text-black disabled:opacity-50">{{ saving ? 'Guardando...' : 'Guardar horario' }}</button></form></div></template>
